# Generated by Django 4.1.5 on 2023-01-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="guid",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
