# Generated by Django 4.1.5 on 2023-01-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_guid_alter_news_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="description",
        ),
    ]
